---
- name: Create a Linux user with SSH access
  hosts: all
  become: true
  vars:
    user_name: ""
    user_uid: ""
    user_groups: ["sudo"]
    user_shell: "/bin/bash"
    user_authorized_keys: []
  roles:
    - user

